# Generated by Django 3.1.5 on 2021-01-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
